### ISSUE TITLE
Improve design of OAuth success HTML page

### ISSUE THREAD

**Issue by imjasonh** [sigstore/sigstore#426] opened 2022-05-07 17:55 UTC
**Description**

Currently, when you successfully get through an OAuth flow, you're met with this page:

<img width="506" alt="Screen Shot 2022-05-07 at 1 51 41 PM" src="https://user-images.githubusercontent.com/210737/167265980-2a90f726-50db-44db-a53f-98db93d3ff1f.png">

Good stuff:
- it's small and simple
- it's fast to load
- it's clear about what to do next

Bad stuff:
- it's black Times New Roman on white background (not Sigstore branding)

I think we have an opportunity to make this page feel really cohesive with the rest of the Sigstore brand. We shouldn't take this as an opportunity to load the page down with a bunch of CSS/JS/images, but I think there's improvements we could make, like:

- add a Sigstore logo
- use Sigstore's font/coloring
- ~~add a button to close, or maybe even "press space to close" -- JS won't let you close a window without some user action, but I think keyboard event should work.~~ edit: browsers no longer allow this

After https://github.com/sigstore/sigstore/pull/425 we'll only have one copy of this HTML, here:

https://github.com/sigstore/sigstore/blob/9a39e97a01521211a31ecc8c29ecf4545be3a73f/pkg/oauth/interactive.go#L19-L25

**Comment by AliAkberAakash** [comment] 2022-05-08 02:59
Would like to work on this

**Comment by znewman01** [comment] 2022-12-21 21:08
Duplicate of #732

**Closed by znewman01** 2022-12-21 21:08 UTC
Labels: enhancement
